# coding:utf-8

IMAGE_CODE_VALIDITY = 300
SMS_CODE_VALIDITY = 600

HOME_PAGE_MAX_HOUSES = 5
HOME_PAGE_DATA_REDIS_EXPIRE_SECOND = 7200

HOUSE_LIST_PAGE_CAPACITY = 3
HOUSE_LIST_REDIS_CACHED_PAGE = 2
HOUSE_LIST_REDIS_EXPIRE_SECOND = 3600
HOUSE_DETAIL_REDIS_EXPIRE_SECOND = 7200

HOUSE_DETAIL_COMMENT_DISPLAY_COUNT = 30